import { Resource } from '../types';

// Mock data for resources
export const resources: Resource[] = [
  {
    id: '1',
    title: 'Calculus Basics',
    description: 'Fundamental concepts of calculus including limits, derivatives, and integrals',
    category: 'Mathematics',
    access: 'public',
    imageUrl: 'https://via.placeholder.com/400x300/FFD700/000000?text=Calculus',
    status: 'approved',
    uploader: 'user1',
    importance: 'high',
    dueDate: 'Today',
    courseName: 'Mathematics 101',
    createdAt: new Date('2025-04-10'),
    updatedAt: new Date('2025-04-10')
  },
  {
    id: '2',
    title: 'World War II Overview',
    description: 'Comprehensive overview of World War II including key events, figures, and outcomes',
    category: 'History',
    access: 'private',
    imageUrl: 'https://via.placeholder.com/400x300/87CEEB/000000?text=World+War+II',
    status: 'pending review',
    uploader: 'user2',
    importance: 'medium',
    dueDate: 'Tomorrow',
    courseName: 'History 202',
    createdAt: new Date('2025-04-15'),
    updatedAt: new Date('2025-04-16')
  },
  {
    id: '3',
    title: 'Shakespeare\'s Sonnets',
    description: 'Analysis of Shakespeare\'s sonnets with focus on themes, structure, and literary devices',
    category: 'Literature',
    access: 'public',
    imageUrl: 'https://via.placeholder.com/400x300/90EE90/000000?text=Shakespeare',
    status: 'approved',
    uploader: 'user3',
    importance: 'low',
    dueDate: 'Next week',
    courseName: 'English Literature',
    createdAt: new Date('2025-04-05'),
    updatedAt: new Date('2025-04-07')
  },
  {
    id: '4',
    title: 'Quantum Physics Principles',
    description: 'Introduction to quantum mechanics and its applications in modern physics',
    category: 'Physics',
    access: 'public',
    imageUrl: 'https://via.placeholder.com/400x300/F08080/000000?text=Quantum+Physics',
    status: 'approved',
    uploader: 'user4',
    importance: 'high',
    dueDate: 'Today',
    courseName: 'Physics 301',
    createdAt: new Date('2025-04-01'),
    updatedAt: new Date('2025-04-02')
  },
  {
    id: '5',
    title: 'Database Management Systems',
    description: 'Comprehensive guide to database design, implementation and optimization',
    category: 'Computer Science',
    access: 'private',
    imageUrl: 'https://via.placeholder.com/400x300/20B2AA/000000?text=Database',
    status: 'pending review',
    uploader: 'user1',
    importance: 'medium',
    dueDate: 'Friday',
    courseName: 'Computer Science 202',
    createdAt: new Date('2025-04-20'),
    updatedAt: new Date('2025-04-20')
  },
  {
    id: '6',
    title: 'Advanced Statistics',
    description: 'In-depth statistical analysis methods and their applications',
    category: 'Mathematics',
    access: 'public',
    imageUrl: 'https://via.placeholder.com/400x300/DDA0DD/000000?text=Statistics',
    status: 'approved',
    uploader: 'user2',
    importance: 'medium',
    dueDate: 'Next Monday',
    courseName: 'Statistics 301',
    createdAt: new Date('2025-04-18'),
    updatedAt: new Date('2025-04-19')
  },
  {
    id: '7',
    title: 'Ancient Civilizations',
    description: 'Study of ancient civilizations and their impact on modern society',
    category: 'History',
    access: 'public',
    imageUrl: 'https://via.placeholder.com/400x300/CD853F/000000?text=Ancient+History',
    status: 'approved',
    uploader: 'user3',
    importance: 'low',
    dueDate: 'Next month',
    courseName: 'History 101',
    createdAt: new Date('2025-04-22'),
    updatedAt: new Date('2025-04-22')
  },
  {
    id: '8',
    title: 'Programming Fundamentals',
    description: 'Basic programming concepts and algorithms',
    category: 'Computer Science',
    access: 'private',
    imageUrl: 'https://via.placeholder.com/400x300/4682B4/000000?text=Programming',
    status: 'pending review',
    uploader: 'user4',
    importance: 'high',
    dueDate: 'Tomorrow',
    courseName: 'CS 101',
    createdAt: new Date('2025-04-23'),
    updatedAt: new Date('2025-04-24')
  },
  {
    id: '9',
    title: 'Organic Chemistry',
    description: 'Study of organic compounds and their reactions',
    category: 'Chemistry',
    access: 'public',
    imageUrl: 'https://via.placeholder.com/400x300/98FB98/000000?text=Chemistry',
    status: 'approved',
    uploader: 'user1',
    importance: 'high',
    dueDate: 'Next week',
    courseName: 'Chemistry 201',
    createdAt: new Date('2025-04-25'),
    updatedAt: new Date('2025-04-25')
  },
  {
    id: '10',
    title: 'Environmental Science',
    description: 'Study of environmental systems and human impact',
    category: 'Biology',
    access: 'public',
    imageUrl: 'https://via.placeholder.com/400x300/87CEEB/000000?text=Environment',
    status: 'approved',
    uploader: 'user2',
    importance: 'medium',
    dueDate: 'Friday',
    courseName: 'Biology 202',
    createdAt: new Date('2025-04-24'),
    updatedAt: new Date('2025-04-24')
  }
];
